insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Hasta la vista, baby', 'Swarzeneggar');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Its not a tumor!', 'Swarzeneggar');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'All the worlds a stage, and all the men and women only players', 'Shakespeare');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #1', 'Hamilton');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #2', 'Hamilton');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #3', 'Hamilton');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #4', 'Hamilton');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #5', 'Hamilton');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #6', 'Hamilton');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #7', 'Hamilton');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #8', 'Hamilton');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #9', 'Hamilton');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #10', 'Hamilton');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #11', 'Hamilton');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #12', 'Hamilton');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #13', 'Hamilton');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #14', 'Hamilton');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #15', 'Hamilton');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #16', 'Hamilton');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #17', 'Shakespeare');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #18', 'Shakespeare');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #19', 'Shakespeare');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #20', 'Shakespeare');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #21', 'Shakespeare');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #22', 'Shakespeare');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #23', 'Shakespeare');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #24', 'Shakespeare');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #25', 'Shakespeare');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #26', 'Shakespeare');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #27', 'Shakespeare');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #28', 'Shakespeare');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #29', 'Shakespeare');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #30', 'Shakespeare');
insert into Quote(id, text, author) values (nextval('hibernate_sequence'), 'Test Quote #31', 'Shakespeare');
