insert into Quote(id, text, author) values (hibernate_sequence.nextval, 'Hasta la vista, baby', 'Swarzeneggar');
insert into Quote(id, text, author) values (hibernate_sequence.nextval, 'Its not a tumor!', 'Swarzeneggar');
insert into Quote(id, text, author) values (hibernate_sequence.nextval, 'All the worlds a stage, and all the men and women only players', 'Shakespeare');
insert into Quote(id, text, author) values (hibernate_sequence.nextval, 'Test Quote #1', 'Hamilton');
insert into Quote(id, text, author) values (hibernate_sequence.nextval, 'Test Quote #2', 'Hamilton');
insert into Quote(id, text, author) values (hibernate_sequence.nextval, 'Test Quote #3', 'Hamilton');
insert into Quote(id, text, author) values (hibernate_sequence.nextval, 'Test Quote #4', 'Hamilton');
insert into Quote(id, text, author) values (hibernate_sequence.nextval, 'Test Quote #5', 'Hamilton');
insert into Quote(id, text, author) values (hibernate_sequence.nextval, 'Test Quote #6', 'Hamilton');
insert into Quote(id, text, author) values (hibernate_sequence.nextval, 'Test Quote #7', 'Hamilton');
insert into Quote(id, text, author) values (hibernate_sequence.nextval, 'Test Quote #8', 'Hamilton');
insert into Quote(id, text, author) values (hibernate_sequence.nextval, 'Test Quote #9', 'Hamilton');
insert into Quote(id, text, author) values (hibernate_sequence.nextval, 'Test Quote #10', 'Hamilton');
insert into Quote(id, text, author) values (hibernate_sequence.nextval, 'Test Quote #11', 'Hamilton');
insert into Quote(id, text, author) values (hibernate_sequence.nextval, 'Test Quote #12', 'Hamilton');
insert into Quote(id, text, author) values (hibernate_sequence.nextval, 'Test Quote #13', 'Hamilton');
insert into Quote(id, text, author) values (hibernate_sequence.nextval, 'Test Quote #14', 'Hamilton');
insert into Quote(id, text, author) values (hibernate_sequence.nextval, 'Test Quote #15', 'Hamilton');
insert into Quote(id, text, author) values (hibernate_sequence.nextval, 'Test Quote #16', 'Hamilton');
